* DONE Clean up streaming connection shutdown
  CLOSED: [2014-03-24 Mon 23:12]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2014-03-24 Mon 23:12]
  :END:
  - 2014-03-24 21:54:40,780 WARNI [puppyserv.webcam][Thread-2]
    Streaming failed: 'NoneType' object has no attribute 'recv'
* DONE Fix still capture stuff and "no connection" image?
  CLOSED: [2014-03-24 Mon 23:13]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2014-03-24 Mon 23:13]
  :END:
* STARTED Throttling
  :LOGBOOK:
  - State "STARTED"    from "DONE"       [2014-03-25 Tue 07:22]
  - State "DONE"       from "TODO"       [2014-03-24 Mon 10:47]
  :END:
  Set an overmal limit on outgoing frames/sec (or kb/sec?)
  and share it equally between clients.

  FIXME: this could be better.  Currently we limit the framerate
  to each client to max_rate / n_clients.   If there are slow clients
  it might be better to let the fast clients have the extra frames.
  But need to do this in a fair way, somehow so that certain clients
  can't hog all the frames.

* DONE Google analytics
  CLOSED: [2014-03-25 Tue 07:22]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2014-03-25 Tue 07:22]
  :END:

* TODO Buildout
  - [ ] Move supervisor config into buildout
  - [ ] Move nginx config into buildout
  - [ ] Set perms on log dir a uwsgi socket
* DONE Check request_method
  CLOSED: [2014-03-26 Wed 07:46]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2014-03-26 Wed 07:46]
  :END:
  Handle HEAD correctly, returns error for other methods

* DONE Fix the Failsafe stream still stream starting logic.
  CLOSED: [2014-03-26 Wed 08:49]
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2014-03-26 Wed 08:49]
  :END:
  Maybe don't start still stream until video stream misses one whole timeout
